# Generated by Django 2.2.9 on 2020-04-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
